# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Vincentqyw"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Planning": 
        filters: ["Path Planning", "Motion Planning", "Trajectory Planning",
                  "Path Following", "Motion Control", "Motion Generation",
                  "Path Optimization", "Trajectory Optimization"]
    "Robot Learning":
        filters: ["Robot Learning", "Learning from Demonstration", "Imitation Learning", 
                  "Skill Learning", "Reinforcement Learning","Task Learning"]
    "Enbodied Robotics":
        filters: ["Enbodied Robotics","vision-language-action(vla)"]
    "PINN":
        filters: ["PINN", "physics-informed neural networks"]
